### ISSUE TITLE
Robust production of base ontologies

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBO-Dashboard#20]
Currently base ontologies are produced like this:

https://github.com/OBOFoundry/OBO-Dashboard/blob/3a5a7da7a26024eb32c9d80b5e6750e3019df4d6/Makefile#L96-L102

This runs a python script which parses the json-ld context file

This fails for dpo, because dpo doesn't mint any classes in its own namespace. We would like 'fbcv' to be returned for dpo.

This may also fail for application ontologies that produce few or no classes in their own namespace. In fact we need to think about what it means to evaluate an 'application ontology' (an ill-defined term). 

I suggest that the value of `--base-iri` is obtained by checking for `preferred_prefix` in the full metadata file. If it does not exist, it is just the default.

This fixes the issue for dpo

**Comment by cmungall** [comment]
As an example of the application ontology issue, making cido.owl produces an ontology with headers but no entities. This ends up passing most tests since there are no violations, but it's just odd to evaluate an empty ontology.

Maybe the definition of an application ontology is: an ontology that should be evaluated via it's standard purl rather than it's base

**Comment by jamesaoverton** [comment]
It would also be good to use the base files provided by the project when available. The best option might be a convention on the filename (`-base`?) in the `products` list in the registry entry for the ontology.

**Comment by cmungall** [comment]
I started adding some explicit bases:

https://github.com/OBOFoundry/OBOFoundry.github.io/commit/63bb944f4c840c43861ac0c3a9c446891f90e8f2

But these are not typed yet..

So perhaps the order of precedence should be:

 1. use a product explicitly typed as base
 2. if not available, use a product with name `*-base.owl`
 3. if not available:
     - if application ontology, use standard purl
     - otherwise, use the existing robot remove command, with the fix above

given the complexity I think this best done in python, not yq, Bill

**Comment by wdduncan** [comment]
@cmungall not sure what you mean by "use a product explicitly typed as base". Do you mean ontologies ids that have '-base'; e.g. 'id: go/go-base.owl'?

**Comment by matentzn** [comment]
I think he means this: https://github.com/INCATools/ontology-development-kit/blob/28706b12c57b30a231fe824a2057bd765b9f2d98/template/src/ontology/Makefile.jinja2#L274

**Comment by wdduncan** [comment]
@matentzn Thanks!

**Comment by cmungall** [comment]
I was actually meaning using the information in the obo central metadata files

for example, you see uberon has a product registered:

```
- id: uberon/bridge/uberon-bridge-to-zfa.owl
   type: BridgeOntology
   page: https://github.com/obophenotype/uberon/wiki/inter-anatomy-ontology-bridge-ontologies
   title: Uberon bridge to ZFA
   description: Taxonomic equivalence axioms connecting zebrafish-specific classes to generic uberon counterparts
   connects:
     - id: uberon
     - id: zfa
```

the values for this type field are a little add hoc, and predate http://purl.obolibrary.org/obo/IAO_8000000

however, the ontology header could also be introspected
